# Numpy Array

In [2]:
import numpy as np
np.array([1, 2, 3],ndmin=2)

array([[1, 2, 3]])

In [3]:
type([1, 2, 3])

list

In [3]:
#Upcasting:

In [4]:
np.array(['1', 2,9.0])

array(['1', '2', '9.0'], dtype='<U3')

In [5]:
#two dimensions

In [4]:
a = np.array([[1, 2], [3, 4], [4,5]])
a.dtype

dtype('int32')

In [7]:
#Minimum dimensions 2:

In [9]:
#dtype

In [11]:
 np.array([1.4, 2, 3], dtype=float)

array([1.4, 2. , 3. ])

In [20]:
#Creating array using .mat (matrix)
np.array(np.mat('1 2 3; 3 4 5'))

array([[1, 2, 3],
       [3, 4, 5]])

In [19]:
#Convert a list into an array:

In [21]:
 a = [1, 2]
np.array(a)

array([1, 2])

In [24]:
b=np.asarray(a)

In [25]:
b

array([1, 2])

In [32]:
# unique id for life time
id(a)

2202107782528

# numpy.fromfunction

In [55]:
#Construct an array by executing a function over each coordinate.

In [56]:
def test(i , j ):
    if i ==j :
        return True 
    else :
        return False 

In [39]:
#Compares row and column location
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

# data types

In [73]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [42]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape) #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype) #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix:  (3, 3)
Data type of this matrix:  int32


# arange and linspace

In [49]:
import numpy as np 

In [48]:
list(range(2,10,2))

[2, 4, 6, 8]

In [51]:
a = np.arange(2,10.5,.4)
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [55]:
#Reverse order
a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [56]:
for i in np.arange(2,10.5,.4):
    print(i)

2.0
2.4
2.8
3.1999999999999997
3.5999999999999996
3.9999999999999996
4.3999999999999995
4.799999999999999
5.199999999999999
5.6
5.999999999999999
6.399999999999999
6.799999999999999
7.199999999999999
7.599999999999999
7.999999999999998
8.399999999999999
8.799999999999999
9.2
9.599999999999998
9.999999999999998
10.399999999999999


In [58]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5]


In [60]:
print("linearly spaced numbers between 1 and 5\n--------------------------------------------")
print(np.linspace(1,5,10))

linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


# Matrix creation

In [299]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [62]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [63]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [89]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [90]:
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5)))

Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [77]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [79]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [92]:
# retstep is the stepsize seperating from samples
np.linspace(2.0, 3.0, num=4, retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [93]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [94]:
#base**start
np.logspace(2.0, 3.0, num=4, base=3.0)

array([ 9.        , 12.98024613, 18.72075441, 27.        ])

In [97]:
#Construct diagonal matrix
x = np.arange(25).reshape(((5,5)))

In [98]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [104]:
np.diag(x , k = -1)

array([ 5, 11, 17, 23])

In [105]:
np.diag(x, k=-2)

array([10, 16, 22])

In [107]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0, 12,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 24]])

In [112]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [113]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [111]:
np.diagflat([1,2,3], 4)

array([[0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [115]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [113]:
np.tri(5, 3, -1, dtype=int)

array([[0, 0, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [178]:
np.tri(7,9 ,-1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0.]])

# Random number generation

In [118]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(10,5)) 

Random number generation (from Uniform distribution)
[[0.87128461 0.16619931 0.75052783 0.07293897 0.20506567]
 [0.33203214 0.21688916 0.33447966 0.14662574 0.98459472]
 [0.819848   0.68281456 0.81638256 0.05305189 0.53356361]
 [0.85297845 0.91370094 0.40521422 0.64883352 0.27336102]
 [0.0921941  0.88080053 0.38069766 0.85024191 0.0720354 ]
 [0.42901441 0.7483071  0.33434843 0.99358218 0.94406341]
 [0.00447176 0.23726081 0.96456139 0.51620065 0.36333891]
 [0.21106167 0.60882437 0.05207734 0.42682894 0.25027655]
 [0.18096358 0.94994161 0.5840624  0.64061709 0.41775071]
 [0.04804065 0.27643903 0.7768802  0.76255253 0.21242341]]


In [119]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.18175841 -2.78157111  2.00167458]
 [-0.18162944 -0.26970322  1.92805331]
 [ 1.04802065  0.30167688  0.73354972]
 [ 0.8079143  -0.38905201 -0.19702783]]


In [190]:
print("Random integer vector:",np.random.randint(1,10,100)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random integer vector: [6 5 7 2 9 5 6 2 3 7 9 8 5 4 6 8 6 6 4 6 1 7 8 6 8 7 5 5 3 1 1 6 9 5 9 2 5
 8 6 8 8 1 5 3 2 6 7 8 6 8 6 6 2 7 5 5 2 6 7 5 7 5 3 1 7 1 6 1 7 5 9 7 6 4
 6 7 6 8 8 4 4 5 2 5 2 7 4 2 6 2 2 8 3 3 9 2 8 6 5 4]

Random integer matrix
[[82 53 58 44]
 [98 84  9 24]
 [43 81 97 51]
 [44 10 46 83]]

20 samples drawn from a dice throw: [2 6 1 2 5 2 1 1 4 2 5 4 5 6 5 4 2 6 2 1]


# Reshaping

In [127]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)


In [365]:
a

array([54, 98, 55, 11, 64, 98, 89, 87, 70, 21,  4, 70, 33, 47, 37, 98, 51,
       67, 47, 64,  7, 84, 38, 65, 47,  1, 72, 64, 52, 40])

In [366]:
b

array([[[54, 98, 55, 11, 64],
        [98, 89, 87, 70, 21],
        [ 4, 70, 33, 47, 37]],

       [[98, 51, 67, 47, 64],
        [ 7, 84, 38, 65, 47],
        [ 1, 72, 64, 52, 40]]])

In [133]:
c

array([[48, 64, 88, 66, 33],
       [43, 85, 75, 11, 73],
       [87, 33,  5, 95, 25],
       [36, 49, 81, 56, 73],
       [66, 25,  1, 24, 53],
       [35, 34,  5, 59, 37]])

In [367]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)



Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [368]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [54 98 55 11 64 98 89 87 70 21  4 70 33 47 37 98 51 67 47 64  7 84 38 65
 47  1 72 64 52 40] 
 --------------------

b looks like
 -------------------- 
 [[[54 98 55 11 64]
  [98 89 87 70 21]
  [ 4 70 33 47 37]]

 [[98 51 67 47 64]
  [ 7 84 38 65 47]
  [ 1 72 64 52 40]]] 
 --------------------

c looks like
 -------------------- 
 [[54 98 55 11 64]
 [98 89 87 70 21]
 [ 4 70 33 47 37]
 [98 51 67 47 64]
 [ 7 84 38 65 47]
 [ 1 72 64 52 40]] 
 --------------------


In [369]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort'))



Vector of random integers
 -------------------------------------------------- 
 [58 52 22 35  6 65 73 63 19 19]

Here is the sorted vector
 -------------------------------------------------- 
 [ 6 19 19 22 35 52 58 63 65 73]


In [138]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[51 48 36 39 16]
 [35 11 87 86 34]
 [85 90 16 32 40]
 [50 13 63 13  5]
 [60 38 55 93 87]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[16 36 39 48 51]
 [11 34 35 86 87]
 [16 32 40 85 90]
 [ 5 13 13 50 63]
 [38 55 60 87 93]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[35 11 16 13  5]
 [50 13 36 32 16]
 [51 38 55 39 34]
 [60 48 63 86 40]
 [85 90 87 93 87]]


In [140]:
M

array([[51, 48, 36, 39, 16],
       [35, 11, 87, 86, 34],
       [85, 90, 16, 32, 40],
       [50, 13, 63, 13,  5],
       [60, 38, 55, 93, 87]])

In [141]:
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[35 11 16 13  5]
 [50 13 36 32 16]
 [51 38 55 39 34]
 [60 48 63 86 40]
 [85 90 87 93 87]]


In [142]:
a

array([48, 64, 88, 66, 33, 43, 85, 75, 11, 73, 87, 33,  5, 95, 25, 36, 49,
       81, 56, 73, 66, 25,  1, 24, 53, 35, 34,  5, 59, 37])

In [143]:
b

array([[[48, 64, 88, 66, 33],
        [43, 85, 75, 11, 73],
        [87, 33,  5, 95, 25]],

       [[36, 49, 81, 56, 73],
        [66, 25,  1, 24, 53],
        [35, 34,  5, 59, 37]]])

In [144]:
print("Max of a:", a.max())
print("Max of b:", b.max())

Max of a: 95
Max of b: 95


# Indexing and slicing

In [145]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [146]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [147]:
print("Elements from 3rd to 5th index are:", arr[3:6])


Elements from 3rd to 5th index are: [3 4 5]


In [148]:
print("Elements up to 4th index are:", arr[:4])


Elements up to 4th index are: [0 1 2 3]


In [155]:
print("Elements from last backwards are:", arr[-1::-2])


Elements from last backwards are: [10  8  6  4  2  0]


In [166]:
print("7 Elements from last backwards are:", arr[-1:-8:-1])


7 Elements from last backwards are: [10  9  8  7  6  5  4]


In [167]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [230]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [168]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[0][2])



Double bracket indexing
------------------------
Element in row index 1 and column index 2: 3.0


In [171]:
mat

array([[1.1, 2. , 3. ],
       [4. , 5.2, 6. ],
       [7. , 8.3, 9. ]])

In [175]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,1])


Entire row at index 2: [7.  8.3 9. ]
Entire column at index 3: [2.  5.2 8.3]


In [178]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:2,1:2])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[5.2]]


In [180]:
mat

array([[1.1, 2. , 3. ],
       [4. , 5.2, 6. ],
       [7. , 8.3, 9. ]])

In [179]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,2]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[2.  3. ]
 [5.2 6. ]]


# Subseting

In [384]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


Matrix of random 2-digit numbers
--------------------------------
 [[62 12 57 64 88]
 [86 94 52 14 34]
 [57 52 33 80 74]]


In [386]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [62 57 64 88 86 94 52 57 52 80 74]


In [385]:
mat>50

array([[ True, False,  True,  True,  True],
       [ True,  True,  True, False, False],
       [ True,  True, False,  True,  True]])

# Slicing

In [387]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [388]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [389]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [390]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [391]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [181]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[5 6 9]
 [3 9 8]
 [6 2 5]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[1 3 9]
 [1 3 5]
 [3 1 8]]


In [182]:
print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)



Addition
------------------
 [[ 6  9 18]
 [ 4 12 13]
 [ 9  3 13]]

Multiplication
------------------
 [[ 5 18 81]
 [ 3 27 40]
 [18  2 40]]


In [265]:
print("\nDivision\n------------------\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[1.         1.125      1.125     ]
 [1.16666667 8.         1.        ]
 [1.5        1.25       4.        ]]

Lineaer combination: 3*A - 2*B
-----------------------------
 [[ 9 11 11]
 [ 9 22  9]
 [10  7 20]]


In [266]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[109 109 109]
 [107 108 109]
 [106 105 108]]


In [267]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


Exponentiation, matrix cubed here
----------------------------------------
 [[729 729 729]
 [343 512 729]
 [216 125 512]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[3.         3.         3.        ]
 [2.64575131 2.82842712 3.        ]
 [2.44948974 2.23606798 2.82842712]]


# Broadcasting

In [268]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [282]:
start = np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [283]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [284]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [272]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [273]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [180]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+add_scalar)

[[ 100.  100.  100.]
 [ 100.  100.  100.]
 [ 100.  100.  100.]
 [ 100.  100.  100.]]


# Array Math

In [274]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[6 1 1]
 [7 6 4]
 [6 2 4]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[9 2 6]
 [2 8 6]
 [3 6 1]]


In [275]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[2.44948974 1.         1.        ]
 [2.64575131 2.44948974 2.        ]
 [2.44948974 1.41421356 2.        ]]


In [276]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[ 403.42879349    2.71828183    2.71828183]
 [1096.63315843  403.42879349   54.59815003]
 [ 403.42879349    7.3890561    54.59815003]]


In [277]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))



10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.77815125 0.         0.        ]
 [0.84509804 0.77815125 0.60205999]
 [0.77815125 0.30103    0.60205999]]
